# Generated by Django 4.2.1 on 2023-05-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_name_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
