# Generated by Django 4.2.1 on 2023-05-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, default=' ', null=True, verbose_name='内容'),
        ),
    ]
