# Generated by Django 4.2.1 on 2023-05-24 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_rename_category_name_status_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='todo.status', verbose_name='ステータス'),
        ),
    ]
