# Generated by Django 4.2.1 on 2023-05-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(help_text='*', max_length=50, verbose_name='タイトル'),
        ),
    ]
